apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: alpine
          image: alpine:3.18
          command:
            - cat
          tty: true
